### PR TITLE
seo improvements

### PR DESCRIPTION
**Pull request by akshayraichur**
Issue: #7 
I have added proper meta tags with og details

### CODE REVIEW

**Comment by akshayraichur** [comment]
@theevilhead , @Supriya-shashivasan please review my pr

**Comment by theevilhead** [comment]
@akshayraichur can we tweak the titles to "DevFest avatar generator" and somewhere in keywords, we can include "DevFest profile picture generator." But I think "DevFest avatar generator" makes more sense as the main title.
What do you think?

**Comment by akshayraichur** [comment]
Yes, I agree. "DevFest avatar generator" makes sense. 
I will update the title.

**Review by theevilhead — APPROVED** [review]

**Comment by theevilhead** [comment]
@akshayraichur  Also, no need to fork the repo. You can directly work in this repo itself. Check out https://github.com/GDGHubli/devfest-profile-picture-maker/blob/development/CONTRIBUTING.md

**Comment by akshayraichur** [comment]
Got it. 
Thanks

**Comment by theevilhead** [comment]
Deployed, thank you 🙌🍻

**Pull request merged**
